### ISSUE TITLE
IndexError( list index out of range )

### ISSUE THREAD

**Issue by srzhang90s** [GWU-CFD/FlashKit#76]
Dear developer,
Thank you so much for your sharing. This kit is so wonderful and convenient.
I was using it to post-process the output files of Flash-X tutorial [Flow Boiling 2D case.](https://github.com/Flash-X/Workflows/tree/main/incompFlow/FlowBoiling) when I tried to use "**flashkit create xdmf INS_Flow_Boiling -A**" there would be the following errors as the picture shows. I also tried with other options but got the same error- IndexError( list index out of range ). For using "**flashkit create tecplot**" there was no any output. I tried to install the Flashkit both locally and in virtual evironment. Could you please give me any hint? Thank you so much.
By the way, I also couldn't open the tutorial file with the recommended VisIt, but I checked the hdf5_plt_cnt files with **h5dump**, the files should not be damaged. 

I look forward to your reply.
![Screenshot from 2024-08-23 23-07-52](https://github.com/user-attachments/assets/82caa145-504e-4203-8a32-d6637846713a)

Best regards,
Shawn

**Comment by akashdhruv** [comment]
Hello Shawn,

Flash-X does not support tecplot yet. Can you please check if the _hdf5_grd_ are being written? Also you are using a very old version of Flash-X.

I would recommend using the latest version from the repository. You can get access here: https://github.com/Flash-X
It will ask you to send an email to Argonne with your GitHub id.

**Comment by akashdhruv** [comment]
Also you may want to use my fork of FlashKit. I made some updates there specifically for Flash-X: https://github.com/akashdhruv/FlashKit

**Comment by srzhang90s** [comment]
> Hello Shawn,
> 
> Flash-X does not support tecplot yet. Can you please check if the _hdf5_grd_ are being written? Also you are using a very old version of Flash-X.
> 
> I would recommend using the latest version from the repository. You can get access here: https://github.com/Flash-X It will ask you to send an email to Argonne with your GitHub id.

Dear Akash,  
Thank you so much for your reply. 
Yes, there was only one **hdf5_grd_0000** generated at the beginning of the simulation. My first goal was to see the results of that tutorial case, I tried FlashKit after VisIt failed to open the hdf5_plt_cnt_ files properly. Actually, I created the Issue in **Flash-X /Workfows** repository first, which was also updated by you, right? So do you have any further suggestions for the existing results? Thanks.
At the moment I have the access of Flash-X approved by @adubey64, thank you.

Best,
Shawn

**Comment by srzhang90s** [comment]
> Also you may want to use my fork of FlashKit. I made some updates there specifically for Flash-X: https://github.com/akashdhruv/FlashKit

Hello Akash,
Thank you so much for sharing this, I will try it later. Thanks a lot.

**Comment by akashdhruv** [comment]
> Also you may want to use my fork of FlashKit. I made some updates there specifically for Flash-X: https://github.com/akashdhruv/FlashKit

Try with this version of FlashKit.

**Comment by srzhang90s** [comment]
> > Also you may want to use my fork of FlashKit. I made some updates there specifically for Flash-X: https://github.com/akashdhruv/FlashKit
> 
> Try with this version of FlashKit.

Thank you for your prompt response. Sure, I will try it and give you feedback.

**Comment by srzhang90s** [comment]
> > Also you may want to use my fork of FlashKit. I made some updates there specifically for Flash-X: https://github.com/akashdhruv/FlashKit
> 
> Try with this version of FlashKit.

Hello Akash,
Thank you once again for your reply. 
This version of FlashKit works. The only small problem was that it's not backward compatible with the version of 'numpy' dependency, at least in my OS. Thanks a lot.

Best,
Shawn

**Comment by akashdhruv** [comment]
> Hello Akash, Thank you once again for your reply. This version of FlashKit works. The only small problem was that it's not backward compatible with the version of 'numpy' dependency, at least in my OS. Thanks a lot.

You are welcome. If you notice here:

https://github.com/akashdhruv/FlashKit/commit/efa58317e0d273eafcd130015784f5e6496abb6b

I tie the setup to a specific numpy version.

**Comment by srzhang90s** [comment]
> > Hello Akash, Thank you once again for your reply. This version of FlashKit works. The only small problem was that it's not backward compatible with the version of 'numpy' dependency, at least in my OS. Thanks a lot.
> 
> You are welcome. If you notice here:
> 
> [akashdhruv@efa5831](https://github.com/akashdhruv/FlashKit/commit/efa58317e0d273eafcd130015784f5e6496abb6b)
> 
> I tie the setup to a specific numpy version.

Yes, I changed the code here and then it worked. Thank you.
Have a nice weekend.

**Comment by srzhang90s** [comment]
Hello Akash,
May I ask you another question here? 
Could you please let me know if the animation [on this webpage ](https://github.com/akashdhruv/Multiphysics-Simulations) is just from your Flow Boiling 2D case in the **Flash-X /Workfows** repository? Which variable (or derived one) is plotted in the animation? I didn't find such a result from the output files. Thank you so much.

Best,
Shawn
